os: osx
osx_image: xcode11.3
language: swift
script: xcodebuild clean build test -project Randomy.xcodeproj -scheme "Randomy" -sdk iphonesimulator -destination "platform=iOS Simulator,id="8AF1865A-E1E3-4A7B-ABA0-084992A95F58",OS=13.0,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
