os: osx
osx_image: xcode11.4
language: swift
script: xcodebuild clean build test -project Randomy.xcodeproj -scheme "Randomy" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
